Numpy

In [2]:
import numpy
numpy.__version__

'1.26.4'

In [3]:
import numpy as np
np.__version__

'1.26.4'

In [8]:
# NumPy Array Attributes: ONE-MULTI-THREE dimensional array
import numpy as np
np.random.seed(0)  #seed ensures that we get the same random numbers each time

x1 = np.random.randint(10, size = 6)
x2 = np.random.randint(10, size = (4,3))
x3 = np.random.randint(10, size = (2,3,4))
print(x1)
print(x2)

[5 0 3 3 7 9]
[[3 5 2]
 [4 7 6]
 [8 8 1]
 [6 7 7]]


In [9]:
#no of dimension (ndim)
print(x1.ndim)
print(x2.ndim)
print(x3.ndim)

1
2
3


In [11]:
#shape of dimension(rows.columns)
print(x1.shape)
print(x2.shape)
print(x3.shape)

(6,)
(4, 3)
(2, 3, 4)


In [12]:
#size of array (rows*col)
print(x1.size)
print(x2.size)
print(x3.size)

6
12
24


In [14]:
#ATTRIBUTE
x1.dtype #data type of the array

dtype('int32')

In [16]:
#attributes of numpy array are (itemsize and nbytes)
print('x1 itemsize: ', x1.itemsize)
print('x1 nbytes: ', x1.nbytes)

x1 itemsize:  4
x1 nbytes:  24


In [17]:
# Array indexing: For one-dimensional arrays, array indexing is the same as list indexing.

print(x1)
print(x1[4])

[5 0 3 3 7 9]
7


In [26]:
#For multi-dimensional arrays, you can access items with comma-separated tuple of indices.

print(x2)
print('item at row 3, column 3:',x2[3,2])
print('item at row 1, column 3:',x2[2,2])
print('item at row 1, column 3:',x2[0,-2])
print('item at row 1, column 1:',x2[0,0])

[[3 5 2]
 [4 7 6]
 [8 8 1]
 [6 7 7]]
item at row 3, column 3: 7
item at row 1, column 3: 1
item at row 1, column 3: 5
item at row 1, column 1: 3


In [28]:
#update a value using indexing

x2[2,-1] = 3.14159
print(x2)
print("updated item at row 3, column 3: ",x2[2,-1])

[[3 5 2]
 [4 7 6]
 [8 8 3]
 [6 7 7]]
updated item at row 3, column 3:  3


In [29]:
#Array slicing : One dimensional array

import numpy as np
x = np.arange(10)
x

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [32]:
#slicing
print('x[:6]:', x[:7])
print('x[2:]:', x[2:])
print('x[1:6]:', x[1:6])
print('x[2::2]:', x[2::2])   # access every other element starting from the index 2
print('x[::]:', x[::])       # access all elements
print("x[::2]: ", x[::2])     # access every other element starting from the first
print("x[7:3:-1]:", x[7:3:-1]) # index 7 to index 4 decremented by 1

x[:6]: [0 1 2 3 4 5 6]
x[2:]: [2 3 4 5 6 7 8 9]
x[1:6]: [1 2 3 4 5]
x[2::2]: [2 4 6 8]
x[::]: [0 1 2 3 4 5 6 7 8 9]
x[::2]:  [0 2 4 6 8]
x[7:3:-1]: [7 6 5 4]


In [33]:
#Accessing Multi-dimensional subarrays

x2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 3],
       [6, 7, 7]])

In [35]:
#multi-dimension
x2[:3, :2]    # rows => index 0 to 2; columns => index 0 to 1

array([[3, 5],
       [4, 7],
       [8, 8]])

In [36]:
x2[::2, :]      # every other row; all columns

array([[3, 5, 2],
       [8, 8, 3]])

In [37]:
x2[::-2, :-1]    # reverse altogether - both rows and columns

array([[6, 7],
       [4, 7]])

In [39]:
#accessing rows and columns

x2

array([[3, 5, 2],
       [4, 7, 6],
       [8, 8, 3],
       [6, 7, 7]])

In [42]:
x2[:,1]   #second column

array([5, 7, 8, 7])

In [43]:
x2[1,:]  #second row

array([4, 7, 6])

In [47]:
#RESHAPING ARRAYS
z = np.arange(0,10)  #OR np.arange(10)
z

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [48]:
z.ndim

1

In [57]:
z.reshape((1,10))

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [56]:
z.shape

(10,)

In [58]:
# row vector using newaxis
x[np.newaxis,:]

array([[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]])

In [60]:
# column vector using newaxis
x[:, np.newaxis]

array([[0],
       [1],
       [2],
       [3],
       [4],
       [5],
       [6],
       [7],
       [8],
       [9]])

In [61]:
#Concatenate

import numpy as np
x = np.array([2,4,6])
y = np.array([7,8,9])
np.concatenate([x,y])

array([2, 4, 6, 7, 8, 9])

In [66]:
#concatenate more thann 2 array
z = np.array([1,2,3])
np.concatenate([x,y,z])

array([2, 4, 6, 7, 8, 9, 1, 2, 3])

In [71]:
array2d = ([
    [1,2,3],
    [4,5,6]])
np.concatenate([array2d,array2d]) #axis = 0 by default (row) #axis = 1 (column)

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [72]:
np.concatenate([array2d,array2d], axis = 1)

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [80]:
np.vstack([array2d, array2d]) #vertical stack

array([[1, 2, 3],
       [4, 5, 6],
       [1, 2, 3],
       [4, 5, 6]])

In [81]:
np.hstack([array2d, array2d]) #horizontally stack

array([[1, 2, 3, 1, 2, 3],
       [4, 5, 6, 4, 5, 6]])

In [62]:
#SPLITTING OF ARRAYS

x = [1,2,5,6,8,9,3]
x1,x2,x3 = np.split(x, [3,6])
print(x1,x2,x3)

[1 2 5] [6 8 9] [3]


In [64]:
grid = np.arange(9).reshape((3, 3))
grid

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [74]:
#hsplit
left, right = np.hsplit(grid, [2])
print(left)
print(right)

[[0 1]
 [3 4]
 [6 7]]
[[2]
 [5]
 [8]]


In [75]:
#vsplit
upper, lower = np.vsplit(grid, [2])
print(upper)
print(lower)

[[0 1 2]
 [3 4 5]]
[[6 7 8]]


In [79]:
# %timeit compute_reciprocals(array)

In [81]:
x = np.arange(4)

print("x = ", x)
print("x + 5 = ", x + 5)
print("x - 5 = ", x - 5)
print("x * 5 = ", x * 5)
print("x / 5 = ", x / 5)
print("x // 5 = ", x // 5) # floor division

print(" -x = ", -x) # negation (unary operation)
print(" x ** 2 = ", x ** 2) # exponentiation
print(" x % 2 = ", x % 2) # modulus

x =  [0 1 2 3]
x + 5 =  [5 6 7 8]
x - 5 =  [-5 -4 -3 -2]
x * 5 =  [ 0  5 10 15]
x / 5 =  [0.  0.2 0.4 0.6]
x // 5 =  [0 0 0 0]
 -x =  [ 0 -1 -2 -3]
 x ** 2 =  [0 1 4 9]
 x % 2 =  [0 1 0 1]


In [83]:
x = np.array([-2, 4, -10, -6, -1])
abs(x) # built-in absolute function

array([ 2,  4, 10,  6,  1])

In [84]:
#Trigonometric functions

theta = np.linspace(0, np.pi, 3)
theta

array([0.        , 1.57079633, 3.14159265])

In [85]:
print('sin(theta) =', np.sin(theta))
print('cos(theta) =', np.cos(theta))
print('tan(theta) =', np.tan(theta))


sin(theta) = [0.0000000e+00 1.0000000e+00 1.2246468e-16]
cos(theta) = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
tan(theta) = [ 0.00000000e+00  1.63312394e+16 -1.22464680e-16]


In [90]:
#Exponents and logarithms
#exponents
x = [2,3,4,5]
print('x =', x)
print('e^x=', np.exp(x))
print('2^x=', np.exp2(x))
print('3^x=', np.power(3,x))

x = [2, 3, 4, 5]
e^x= [  7.3890561   20.08553692  54.59815003 148.4131591 ]
2^x= [ 4.  8. 16. 32.]
3^x= [  9  27  81 243]


In [95]:
#logarithms

x = [4,6,8,9]

print('x=', x)
print('ln(x):', np.log(x))
print('log2(x):', np.log2(x))
print('log10(x):', np.log10(x))

x= [4, 6, 8, 9]
ln(x): [1.38629436 1.79175947 2.07944154 2.19722458]
log2(x): [2.        2.5849625 3.        3.169925 ]
log10(x): [0.60205999 0.77815125 0.90308999 0.95424251]
